### 공통 (all)
pipeline: valid    # option: ['train', 'valid', 'test', 'pred']
model_name: pickt
data_name: dbekt22

model_path: /home/jovyan/work/repo/models/DBE-KT22/pickt_train/checkpoints/pickt-dbekt22-epoch=19-auc_micro=0.8004.pt
km_data_path: /home/jovyan/work/PICKT/data/DBE-KT22/preprocessed/km_data.json
output_dir: /home/jovyan/work/repo/models/DBE-KT22/pickt_valid

valid_dataset_path: /home/jovyan/work/PICKT/data/DBE-KT22/preprocessed/valid_datasets.json
threshold: 0.5

seed: 42


## 검증 및 테스트 (validate & test)
valid_batch_size: 32
valid_num_workers: 0
limit_val_batches: 1.0


## device 설정
accelerator: gpu        # option: ['cpu', 'gpu', 'auto']  /  tpu, hpu 사용 불가
strategy: single_device           # option: ['single_device', 'ddp', 'fsdp', 'deepspeed']

deterministic: true    # gpu 연산을 해도 재현성이 유지되기 위해 true 로 설정
benchmark: true    # deterministic=True 면 자동으로 False 로 설정됨. cpu 사용 시 해당 옵션은 의미가 없음.
sync_batchnorm: true    # 분산환경(DDP, FSDP 등)에서만 의미가 있음. 단일 장치(cpu, single gpu)에서 효과 없거나 무시됨.