name: pickt
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.10.16=habfa6aa_3_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=78.1.0=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - comm==0.2.2
      - debugpy==1.8.14
      - decorator==5.2.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastexcel==0.14.0
      - filelock==3.18.0
      - frozenlist==1.5.0
      - fsspec==2025.3.2
      - grpcio==1.71.0
      - huggingface-hub==0.30.2
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.35.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - lightning==2.5.1
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - markdown==3.8
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.4.3
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==2.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.7
      - polars==1.29.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - torch==2.5.0
      - torch-geometric==2.6.1
      - torchmetrics==1.7.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.1
      - triton==3.1.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - umap-learn==0.5.7
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - yarl==1.19.0
prefix: /opt/conda/envs/pickt
